### ISSUE TITLE
Wrong version tag

### ISSUE THREAD

**Issue by Kyslik** [TZK-/TaigaLaravel#4]
I guess you made a mistake, take a look at https://packagist.org/packages/tzk/taiga-laravel as you can see there is no version **1.0.0**, I guess you should make new tag **1.2.0** so its clear for everyone.

Also delete current **1.0.0** tag since composer treats it as **1.0**.

Thanks

**Comment by TZK-** [comment]
Yes indeed I made a mistake on the tag name. I've just renamed it to v1.1.0.
